# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hm6EOLUv82HKL-0Hems9WJs2xvZkV9gn
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from google.colab import files

# 1. Tải dữ liệu
print("Đang chờ tải file...")
uploaded = files.upload()
filename = "shopping_behavior_updated.xlsx"

try:
    if len(uploaded) > 0:
        filename = list(uploaded.keys())[0]
    df = pd.read_excel(filename)
    print("Tải dữ liệu thành công!")
except FileNotFoundError:
    print("Không tìm thấy file. Vui lòng kiểm tra lại.")
except Exception as e:
    print(f"Có lỗi xảy ra: {e}")

# 2. Làm sạch và Chuẩn hóa
if 'df' in locals():
    df.drop_duplicates(inplace=True)
    df.columns = [col.lower().replace(' ', '_').replace('(', '').replace(')', '') for col in df.columns]

    # 3. Tính toán dữ liệu cho biểu đồ
    # Doanh thu theo danh mục
    category_sales = df.groupby('category')['purchase_amount_usd'].sum().sort_values(ascending=False)

    # Giới tính
    gender_counts = df['gender'].value_counts(normalize=True) * 100

    # Chi tiêu trung bình theo mùa
    season_avg = df.groupby('season')['purchase_amount_usd'].mean().sort_values(ascending=False)

    # 4. Vẽ biểu đồ
    plt.figure(figsize=(18, 12))
    plt.suptitle('BẢNG PHÂN TÍCH HÀNH VI MUA SẮM', fontsize=20, fontweight='bold')

    # Biểu đồ 1: Bar chart doanh thu
    plt.subplot(2, 2, 1)
    sns.barplot(x=category_sales.index, y=category_sales.values, palette='viridis')
    plt.title('Tổng Doanh Thu Theo Danh Mục')
    plt.xlabel('Danh mục')
    plt.ylabel('Doanh thu (USD)')

    # Biểu đồ 2: Pie chart giới tính
    plt.subplot(2, 2, 2)
    plt.pie(gender_counts, labels=gender_counts.index, autopct='%1.1f%%', startangle=140, colors=['#ff9999','#66b3ff'])
    plt.title('Tỷ Lệ Giới Tính Khách Hàng')

    # Biểu đồ 3: Histogram độ tuổi
    plt.subplot(2, 2, 3)
    sns.histplot(df['age'], bins=20, kde=True, color='green')
    plt.axvline(df['age'].mean(), color='red', linestyle='--', label=f'TB: {df["age"].mean():.1f}')
    plt.legend()
    plt.title('Phân Phối Độ Tuổi')

    # Biểu đồ 4: Boxplot chi tiêu theo mùa
    plt.subplot(2, 2, 4)
    sns.boxplot(x='season', y='purchase_amount_usd', data=df, palette='coolwarm')
    plt.title('Phân Bố Chi Tiêu Theo Mùa')

    plt.tight_layout(rect=[0, 0.03, 1, 0.95])
    plt.show()

    # ==============================================================================
    # 5. PHẦN TỰ ĐỘNG SINH NHẬN XÉT (INSIGHTS)
    # ==============================================================================
    print("\n" + "="*50)
    print("TỔNG HỢP NHẬN XÉT VÀ PHÂN TÍCH DỮ LIỆU")
    print("="*50)

    # Nhận xét 1: Về Doanh thu danh mục
    top_cat = category_sales.index[0]
    top_val = category_sales.values[0]
    low_cat = category_sales.index[-1]
    print(f"1. [DANH MỤC SẢN PHẨM]:")
    print(f"   - Danh mục mang lại doanh thu cao nhất là '{top_cat}' với tổng {top_val:,.0f} USD.")
    print(f"   - Danh mục thấp nhất là '{low_cat}', cần xem xét chiến lược kích cầu hoặc cắt giảm.")

    # Nhận xét 2: Về Giới tính
    dom_gender = gender_counts.idxmax()
    dom_pct = gender_counts.max()
    print(f"\n2. [ĐỐI TƯỢNG KHÁCH HÀNG]:")
    print(f"   - Giới tính '{dom_gender}' chiếm đa số với {dom_pct:.1f}%.")
    if abs(gender_counts.values[0] - gender_counts.values[1]) < 10:
        print("   -> Tỷ lệ nam/nữ khá cân bằng, sản phẩm có sức hút với cả hai giới.")
    else:
        print(f"   -> Cần tập trung marketing mạnh hơn vào nhóm '{dom_gender}'.")

    # Nhận xét 3: Về Độ tuổi
    avg_age = df['age'].mean()
    min_age = df['age'].min()
    max_age = df['age'].max()
    print(f"\n3. [ĐỘ TUỔI]:")
    print(f"   - Độ tuổi trung bình của khách hàng là {avg_age:.1f} tuổi.")
    print(f"   - Dải tuổi trải dài từ {min_age} đến {max_age} tuổi.")
    # Kiểm tra phân phối sơ bộ
    if df['age'].skew() > 1:
        print("   -> Phân phối lệch phải: Khách hàng chủ yếu là người trẻ.")
    elif df['age'].skew() < -1:
        print("   -> Phân phối lệch trái: Khách hàng chủ yếu là người lớn tuổi.")
    else:
        print("   -> Phân phối độ tuổi khá đồng đều.")

    # Nhận xét 4: Về Mùa vụ
    best_season = season_avg.index[0]
    worst_season = season_avg.index[-1]
    print(f"\n4. [XU HƯỚNG THEO MÙA]:")
    print(f"   - Khách hàng chi tiêu mạnh tay nhất vào mùa '{best_season}'.")
    print(f"   - Mức chi tiêu thấp nhất rơi vào mùa '{worst_season}'.")
    print("-" * 50)
    # Chia độ tuổi thành các nhóm (Age Group) để dễ phân tích
bins = [18, 30, 50, 100]
labels = ['Young (18-30)', 'Middle-aged (31-50)', 'Senior (50+)']
df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=False)

# 2. VẼ BIỂU ĐỒ PHÂN TÍCH
plt.figure(figsize=(18, 12))
plt.suptitle('BIỂU ĐỒ PHÂN TÍCH: TƯƠNG QUAN DỮ LIỆU', fontsize=20, fontweight='bold', color='darkblue')

# Biểu đồ 5: Heatmap - Mối quan hệ giữa Giới tính và Danh mục sản phẩm
plt.subplot(2, 2, 1)
cat_gender_pivot = pd.crosstab(df['category'], df['gender'])
sns.heatmap(cat_gender_pivot, annot=True, fmt='d', cmap='Blues', linewidths=.5)
plt.title('Sức Mua: Danh Mục vs Giới Tính')

# Biểu đồ 6: Barplot - Chi tiêu trung bình theo Nhóm tuổi
plt.subplot(2, 2, 2)
sns.barplot(x='age_group', y='purchase_amount_usd', data=df, estimator=np.mean, palette='magma', errorbar=None)
plt.title('Chi Tiêu Trung Bình Theo Nhóm Tuổi')
plt.ylabel('Chi tiêu TB (USD)')

# Biểu đồ 7: Boxplot - Đánh giá (Rating) ảnh hưởng thế nào đến Chi tiêu?
plt.subplot(2, 2, 3)
sns.boxplot(x='review_rating', y='purchase_amount_usd', data=df, palette='Set2')
plt.title('Mối Quan Hệ: Điểm Đánh Giá vs Số Tiền Chi Tiêu')

# Biểu đồ 8: Countplot - Phương thức thanh toán phổ biến nhất
plt.subplot(2, 2, 4)
payment_counts = df['payment_method'].value_counts()
sns.barplot(x=payment_counts.values, y=payment_counts.index, palette='cool')
plt.title('Phương Thức Thanh Toán Ưa Chuộng')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

# 3. TỰ ĐỘNG SINH INSIGHT CHIẾN LƯỢC (BUSINESS INTELLIGENCE)
print("\n" + "="*60)
print("CHIẾN LƯỢC KINH DOANH ĐỀ XUẤT (Dựa trên số liệu)")
print("="*60)

# Insight 1: Cross-sell theo giới tính
male_fav = cat_gender_pivot['Male'].idxmax()
female_fav = cat_gender_pivot['Female'].idxmax()

print(f"1. [CHIẾN LƯỢC SẢN PHẨM]:")
print(f"   - Khách hàng NAM tập trung mua nhiều nhất ở danh mục: '{male_fav}'.")
print(f"   - Khách hàng NỮ tập trung mua nhiều nhất ở danh mục: '{female_fav}'.")
if male_fav != female_fav:
    print("   -> Hành vi khác biệt rõ rệt. Cần tách riêng chiến dịch quảng cáo cho Nam và Nữ.")
else:
    print(f"   -> Cả hai giới đều thích '{male_fav}'. Đây là sản phẩm chủ lực (Hero Product).")

# Insight 2: Phân khúc khách hàng theo độ tuổi
age_spend = df.groupby('age_group', observed=True)['purchase_amount_usd'].mean()
rich_group = age_spend.idxmax()
print(f"\n2. [PHÂN KHÚC KHÁCH HÀNG]:")
print(f"   - Nhóm '{rich_group}' đang có mức chi tiêu trung bình cao nhất ({age_spend.max():.2f} USD/đơn).")
print("   -> Đề xuất: Ưu tiên chăm sóc khách hàng VIP và các gói Membership cho nhóm tuổi này.")

# Insight 3: Phương thức thanh toán
top_payment = df['payment_method'].value_counts().idxmax()
print(f"\n3. [TỐI ƯU THANH TOÁN]:")
print(f"   - Phương thức '{top_payment}' được sử dụng nhiều nhất.")
print("   -> Đề xuất: Đảm bảo cổng thanh toán này luôn hoạt động ổn định và có ưu đãi liên kết.")

# Insight 4: Về đánh giá (Rating)
avg_rating = df['review_rating'].mean()
print(f"\n4. [CHẤT LƯỢNG DỊCH VỤ]:")
print(f"   - Điểm đánh giá trung bình toàn sàn là {avg_rating:.2f}/5.0.")
if avg_rating < 3.5:
    print("   -> Cảnh báo: Điểm đánh giá thấp. Cần rà soát lại chất lượng sản phẩm.")
else:
    print("   -> Tích cực: Khách hàng khá hài lòng về dịch vụ.")

print("-" * 60)